[build]
python_version = "3.11.2"

[phases.setup]
cmds = [
    "apt-get update && apt-get install -y python3-pip",
    "python3 -m pip install --upgrade pip",
]

[phases.install]
cmds = [
    "python3 -m pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "python3 manage.py collectstatic --noinput",
]

[start]
cmd = "gunicorn land_viewer.wsgi"
